### ISSUE TITLE
Syntax highlighting in readme

### ISSUE THREAD

**Issue by flowHater** [xdg-go/jibby#4]
To get a pretty syntax highlighting specify golang right after the opening triple backtick.
```golang
func main() {
   fmt.Println("Hello World!")
}
```

And very nice project, have to try it out.

**Comment by xdg** [comment]
Thank you.  I'd love to hear more about what you're using it for.

**Comment by flowHater** [comment]
I tried it, and it works pretty well. I'm using it to transfer data from Postgres to  MongoDB. With complex and nested documents. Initially we used `psql | mongoimport"` as a naive first attempt. But we written a better approach by using Golang and some parts of the `mongo go driver`/`mongorestore` to figure it out that it's only a json-bson conversion. So your package fit perfectly with our use case. So we got from a process taking 1min50 to 1min18 with jibby.

**Comment by xdg** [comment]
Cool.  Glad it helped.  I've merged the PR so I'm closing this ticket.
